# Generated by Django 4.0.4 on 2022-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityAPI', '0002_alter_master_comments_alter_master_compdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='compDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='dueDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
